import { CacheStore, type Metafile } from '@rsaf/bundler';

/**
 * Represents a cached build artifact.
 */
export interface BuildCache {
	/** The raw string or buffer contents of the file. */
	contents: string;
	/** * The classification of the artifact:
	 * - `bundle`: A primary JavaScript/TypeScript entry point or chunk.
	 * - `asset`: A static file (CSS, images, fonts).
	 */
	type: 'asset' | 'bundle';
}

/**
 * Keys used for storing supplemental build information.
 */
type MetaData = 'metafile';

/**
 * A global singleton store for generated build artifacts.
 * * This cache maps relative file paths to their {@link BuildCache} representation.
 * It is primarily used to serve assets from memory during development.
 * * @example
 * ```ts
 * buildCache.set('index.js', { contents: 'console.log("hi")', type: 'bundle' });
 * ```
 */
export const buildCache = new CacheStore<Record<string, BuildCache>>();

/**
 * A global singleton store for esbuild metadata.
 * * Stores the {@link Metafile} generated by esbuild, which contains
 * detailed information about bundle composition, dependencies, and file sizes.
 * * @remarks
 * This is highly useful for generating bundle analysis reports or calculating
 * hash-based filenames for production manifests.
 */
export const metaDataCache = new CacheStore<Record<MetaData, Metafile>>();
